name: PR Preview

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: peter-evans/create-or-update-comment@v2
        id: couc
        with:
          body: ⌛ Deploy Preview - Build in Progress
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.BOT }}

      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          
      - name: Install and Build
        run: |
          npm ci
          npm run build

      - if: ${{ github.event.action == 'preview'}}
        run: gh repo create wdh-bot/website-${{ github.event.pull_request.number }} --public
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BOT }}
          publish_dir: ./build
          external_repository: wdh-bot/website-${{ github.event.pull_request.number }}

      - name: Sleep - Page Gets Updates
        run: sleep 1m
        shell: bash

      - name: comment Preview Ready
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            ✅ Deploy Successful
            🚀 Preview: https://preview.williamharrison.dev/website-${{ github.event.pull_request.number }}
            🔍 Deploy Log: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          comment-id: ${{ steps.couc.outputs.comment-id }}
          edit-mode: replace
          token: ${{ secrets.BOT }}

      - if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            ❌ Deploy Preview Failed
            🔍 Deploy Log: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          comment-id: ${{ steps.couc.outputs.comment-id }}
          edit-mode: replace
          token: ${{ secrets.BOT }}
